version: "3"
services:
  jenkins-master:
    image: jenkins/jenkins
    container_name: jenkins-master
    networks:
      my-net:
        aliases:
          - 'jenkins.master.mark.com'
    restart: always
    ports:
      - "18080:8080"
    volumes:
      - './jenkins_master/jenkins_home:/var/jenkins_home'
  jenkins-slash1:
    image: jenkins/jenkins
    container_name: jenkins-sl1
    networks:
      my-net:
        aliases:
          - 'jenkins.slave1.mark.com'
    restart: always
    ports:
      - "18081:8080"
    volumes:
      - './jenkins_slave1/jenkins_home:/var/jenkins_home'
  jenkins-slash2:
    image: jenkins/jenkins
    container_name: jenkins-sl2
    networks:
      my-net:
        aliases:
          - 'jenkins.slave2.mark.com'
    restart: always
    ports:
      - "18082:8080"
    volumes:
      - './jenkins_slave2/jenkins_home:/var/jenkins_home'
  gitea:
    image: 'gitea/gitea:latest'
    container_name: 'jenkins-gitea'
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    ports:
      - '18090:3000'
      - '18453:443'
      - '18032:22'
    networks:
      my-net:
        aliases:
          - 'gitea.mark.com'
    volumes:
      - './gitea/data:/data'
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: 'jenkins-mysql'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      my-net:
        aliases:
          - 'mysql.mark.com'
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  my-net:
    driver: bridge
