version: "3"
services:
  jenkins-master:
    image: jenkins/jenkins
    container_name: jenkins-master
    networks:
      my-net:
        aliases:
          - 'jenkins.master.mark.com'
    restart: always
    ports:
      - "18002:22"
      - "18080:8080"
    volumes:
      - './jenkins_master/jenkins_home:/var/jenkins_home'
  jenkins-agent1:
    image: jenkins/agent
    command: 'java -jar /usr/share/jenkins/agent.jar -jnlpUrl http://jenkins.master.mark.com:8080/computer/agent1/slave-agent.jnlp -secret 09d615c2aee0411f4e4ee357818ea4640e3163a34b2124689d74f818605d3fee -workDir /home/jenkins/agent'
    container_name: jenkins-agent1
    networks:
      my-net:
        aliases:
          - 'jenkins.agent1.mark.com'
    restart: always
    ports:
      - "18012:22"
      - "18081:8080"
    volumes:
      - './jenkins_agent1:/home/jenkins/agent'
    depends_on:
      - jenkins-master
  jenkins-agent2:
    image: jenkins/agent
    command: 'java -jar /usr/share/jenkins/agent.jar -jnlpUrl http://jenkins.master.mark.com:8080/computer/agent2/slave-agent.jnlp -secret fefa025b63c81b9716cd8025e860eb01b3f284166cb496ff30d069acf56ccd44 -workDir /home/jenkins/agent'
    container_name: jenkins-agent2
    networks:
      my-net:
        aliases:
          - 'jenkins.agent2.mark.com'
    restart: always
    ports:
      - "18022:22"
      - "18082:8080"
    volumes:
      - './jenkins_agent2:/home/jenkins/agent'
    depends_on:
      - jenkins-master
  gitea:
    image: 'gitea/gitea:latest'
    container_name: 'jenkins-gitea'
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    ports:
      - '18090:3000'
      - '18453:443'
      - '18032:22'
    networks:
      my-net:
        aliases:
          - 'gitea.mark.com'
    volumes:
      - './gitea/data:/data'
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: 'jenkins-mysql'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      my-net:
        aliases:
          - 'mysql.mark.com'
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  my-net:
    driver: bridge
